export const users = [
    {
      name: "Tony Reichert",
      role: "Admin",
      status: "Active",
      email: "tony.reichert@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Zoey Lang",
      role: "Editor",
      status: "Inactive",
      email: "zoey.lang@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    {
      name: "Jane Fisher",
      role: "Viewer",
      status: "Active",
      email: "jane.fisher@example.com",
      permissions: ["Read"],
    },
    {
      name: "William Howard",
      role: "Contributor",
      status: "Inactive",
      email: "william.howard@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Sarah Connor",
      role: "Admin",
      status: "Active",
      email: "sarah.connor@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Michael Scott",
      role: "Admin",
      status: "Inactive",
      email: "michael.scott@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Dwight Schrute",
      role: "Editor",
      status: "Active",
      email: "dwight.schrute@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    {
      name: "Pam Beesly",
      role: "Viewer",
      status: "Active",
      email: "pam.beesly@example.com",
      permissions: ["Read"],
    },
    {
      name: "Jim Halpert",
      role: "Contributor",
      status: "Inactive",
      email: "jim.halpert@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Angela Martin",
      role: "Editor",
      status: "Active",
      email: "angela.martin@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    { 
      name: "Stanley Hudson",
      role: "Viewer",
      status: "Inactive",
      email: "stanley.hudson@example.com",
      permissions: ["Read"],
    },
    {
      name: "Kelly Kapoor",
      role: "Contributor",
      status: "Active",
      email: "kelly.kapoor@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Ryan Howard",
      role: "Viewer",
      status: "Inactive",
      email: "ryan.howard@example.com",
      permissions: ["Read"],
    },
    {
      name: "Kevin Malone",
      role: "Contributor",
      status: "Active",
      email: "kevin.malone@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Oscar Martinez",
      role: "Editor",
      status: "Inactive",
      email: "oscar.martinez@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    {
      name: "Holly Flax",
      role: "Admin",
      status: "Active",
      email: "holly.flax@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Jan Levinson",
      role: "Admin",
      status: "Inactive",
      email: "jan.levinson@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "David Wallace",
      role: "Admin",
      status: "Active",
      email: "david.wallace@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Toby Flenderson",
      role: "Viewer",
      status: "Inactive",
      email: "toby.flenderson@example.com",
      permissions: ["Read"],
    },
    {
      name: "Creed Bratton",
      role: "Viewer",
      status: "Active",
      email: "creed.bratton@example.com",
      permissions: ["Read"],
    },
    {
      name: "Meredith Palmer",
      role: "Contributor",
      status: "Inactive",
      email: "meredith.palmer@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Phyllis Vance",
      role: "Contributor",
      status: "Active",
      email: "phyllis.vance@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Andy Bernard",
      role: "Editor",
      status: "Inactive",
      email: "andy.bernard@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    {
      name: "Clark Green",
      role: "Contributor",
      status: "Active",
      email: "clark.green@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Pete Miller",
      role: "Viewer",
      status: "Inactive",
      email: "pete.miller@example.com",
      permissions: ["Read"],
    },
    {
      name: "Robert California",
      role: "Admin",
      status: "Active",
      email: "robert.california@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Jo Bennett",
      role: "Admin",
      status: "Inactive",
      email: "jo.bennett@example.com",
      permissions: ["Read", "Write", "Edit", "Delete"],
    },
    {
      name: "Gabe Lewis",
      role: "Editor",
      status: "Active",
      email: "gabe.lewis@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    {
      name: "Charles Miner",
      role: "Editor",
      status: "Inactive",
      email: "charles.miner@example.com",
      permissions: ["Read", "Write", "Edit"],
    },
    {
      name: "Nellie Bertram",
      role: "Contributor",
      status: "Active",
      email: "nellie.bertram@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Karen Filippelli",
      role: "Contributor",
      status: "Inactive",
      email: "karen.filippelli@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Ed Truck",
      role: "Viewer",
      status: "Active",
      email: "ed.truck@example.com",
      permissions: ["Read"],
    },
    {
      name: "Roy Anderson",
      role: "Viewer",
      status: "Inactive",
      email: "roy.anderson@example.com",
      permissions: ["Read"],
    },
    {
      name: "Darryl Philbin",
      role: "Contributor",
      status: "Active",
      email: "darryl.philbin@example.com",
      permissions: ["Read", "Write"],
    },
    {
      name: "Val Johnson",
      role: "Contributor",
      status: "Inactive",
      email: "val.johnson@example.com",
      permissions: ["Read", "Write"],
    },
  ];
  